#!/usr/bin/env bash
set -o pipefail
set -o errexit
set -o nounset
# set -o xtrace

# Set magic variables for current file & dir
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"

cat <<EOF > website/index.md
---
layout: default
title: BASH3 Boilerplate – the delete-key friendly template for writing better BASH scripts
warning: This page is generated by ${__base}.sh based on README.md, please don't edit index.md directly.
---
EOF
# http://stackoverflow.com/a/7104422/151666
cat README.md |sed -n -e '/<!--more-->/,$p' | tail -n +2 >> website/index.md


cat <<EOF > website/faq.md
---
layout: default
title: FAQ | BASH3 Boilerplate
warning: This page is generated by ${__base}.sh based on README.md, please don't edit faq.md directly.
permalink: /FAQ.md/
---
EOF
cat FAQ.md |sed -n -e '/<!--more-->/,$p' | tail -n +2 >> website/faq.md


cat <<EOF > website/changelog.md
---
layout: default
title: Changelog | BASH3 Boilerplate
warning: This page is generated by ${__base}.sh based on README.md, please don't edit changelog.md directly.
permalink: /CHANGELOG.md/
---
EOF
cat CHANGELOG.md |sed -n -e '/<!--more-->/,$p' | tail -n +2 >> website/changelog.md
